export const apiEndpoints = {
  auth: {
    login: "/Auth/login",
    adminLogin: "/Auth/login",
    me: "/Auth/me",
  },
  admin: {
    users: "/Admin/users",
    dashboard: "/Admin/dashboard",
    dashboardApiStatus: "/Admin/dashboard/api-status",
    dashboardApiCalls: "/Admin/dashboard/api-calls",
    activateUser: (userId: string) => `/Admin/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/Admin/users/${userId}/deactivate`,
    deleteUser: (userId: string) => `/Admin/users/${userId}`,
  },
  papers: {
    list: "/Paper",
    detail: (id: string) => `/Paper/${id}`,
    byAuthor: (authorId: string) => `/Paper/author/${authorId}`,
  },
  authors: {
    detail: (id: string) => `/Author/${id}`,
  },
  search: {
    papers: "/Search/papers",
    paperReindex: "/Search/papers/reindex",
    paperReindexBackground: "/Search/papers/reindex/background",
    paperIndex: "/Search/papers/index",
    paperIndexRecreate: "/Search/papers/index/recreate",
    paperIndexRecreateBackground: "/Search/papers/index/recreate/background",
    authors: "/Search/authors",
    authorReindex: "/Search/authors/reindex",
    authorReindexBackground: "/Search/authors/reindex/background",
    authorIndex: "/Search/authors/index",
    authorIndexRecreate: "/Search/authors/index/recreate",
    authorIndexRecreateBackground: "/Search/authors/index/recreate/background",
  },
  semanticScholar: {
    search: "/SemanticScholar/search",
  },
  user: {
    profile: "/User/profile",
    legacyProfile: "/profile",
    bookmarks: "/User/bookmarks",
    bookmark: (paperId: string) => `/User/bookmarks/${paperId}`,
    followingTopics: "/User/following/topics",
    followingTopic: (topicId: string) => `/User/following/topics/${topicId}`,
  },
  topics: {
    list: "/Topic",
    detail: (id: string) => `/Topic/${id}`,
  },
  journals: {
    list: "/Journal",
    detail: (id: string) => `/Journal/${id}`,
  },
  keyword: {
    suggestions: "/Keyword/suggestions",
  },
  analytics: {
    papersByYear: "/Analytics/trends/papers-by-year",
    citationsByYear: "/Analytics/trends/citations-by-year",
    topTopics: "/Analytics/trends/top-topics",
    topDomains: "/Analytics/trends/top-domains",
    keywordsOverTime: "/Analytics/trends/keywords-over-time",
    topAuthorsByCitations: "/Analytics/authors/top-citations",
    topAuthorsByHIndex: "/Analytics/authors/top-hindex",
    authorCollaborationNetwork: "/Analytics/authors/collaboration-network",
    topJournalsByPaperCount: "/Analytics/journals/top-paper-count",
    topJournalsByCitations: "/Analytics/journals/top-citations",
    journalOpenAccessRatio: "/Analytics/journals/open-access-ratio",
    keywordWordCloud: "/Analytics/keywords/word-cloud",
    topKeywordsByYear: "/Analytics/keywords/top-by-year",
    keywordCoOccurrence: "/Analytics/keywords/co-occurrence",
    topicCoOccurrence: "/Analytics/topics/co-occurrence",
    topicsAvailableForCompare: "/Analytics/topics/available-for-compare",
    topicComparison: "/Analytics/topics/compare",
    journalTracker: "/Analytics/journals/tracker",
    keywordTrends: "/Analytics/keyword-trends",
    topicTrends: "/Analytics/topic-trends",
    trendingTopics: "/Analytics/trending-topics",
    dashboard: "/Analytics/dashboard",
  },
  dashboard: {
    summary: "/Dashboard/summary",
    publicationTrends: "/Dashboard/publication-trends",
    hotTopics: "/Dashboard/hot-topics",
  },
} as const;
